def get_include_domains():
    return ['https://www..getapp.com',
            'https://www..g2.com',
            'https://www..capterra.com',
            'https://www..trustradius.com',
            'https://www..financesonline.com',
            'https://www..clutch.co',
            'https://www..crozdesk.com',
            'https://www..serchen.com',
            'https://www..trustpilot.com',
            'https://www..softwaresuggest.com',
            'https://www..saashub.com',
            'https://www..technologyadvice.com',
            'https://www..peerspot.com',
            'https://www..crowdreviews.com',
            'https://www..appsumo.com',
            'https://www..featuredcustomers.com',
            'https://www..producthunt.com']